### ISSUE TITLE
Bug: hash.merge throws an error when the path is nil

### ISSUE THREAD

**Issue by MonkeyAndres** [redradix/reduken#32]

**Comment by olareoun** [comment]
@MonkeyAndres is this about calling `hash.merge('aDomain', undefined, { foo: 'bar' })` ?
And the error: 

![Screenshot 2020-09-28 at 16 08 14](https://user-images.githubusercontent.com/920785/94443014-f022aa00-01a4-11eb-9b1d-f173b812ce13.png)

**Comment by MonkeyAndres** [comment]
Solved as part of https://github.com/redradix/reduken/pull/31
